# Generated by Django 5.0.6 on 2025-02-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=45, unique=True)),
                ("reason", models.TextField()),
                ("attempts", models.IntegerField(default=0)),
                ("blocked_until", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IP Blacklist",
                "verbose_name_plural": "IP Blacklist",
                "db_table": "ip_blacklist",
            },
        ),
        migrations.CreateModel(
            name="Manifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("manifest_type", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField(null=True)),
                (
                    "manifest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manifest_materials",
                        to="mail_servers.manifest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(null=True)),
                ("log_type", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_to_log",
                        to="mail_servers.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IMAP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server", models.CharField(max_length=255, null=True)),
                ("port", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_to_imap",
                        to="mail_servers.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server", models.CharField(max_length=255, null=True)),
                ("port", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=255, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_to_smtp",
                        to="mail_servers.session",
                    ),
                ),
            ],
            options={
                "db_table": "smtp",
            },
        ),
        migrations.CreateModel(
            name="Temp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempName", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_to_temp",
                        to="mail_servers.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintmp", models.IntegerField(null=True)),
                ("template", models.TextField(null=True)),
                ("froms", models.TextField(null=True)),
                ("subject", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("htmlbodies", models.TextField(null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_to_template",
                        to="mail_servers.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("tempName", models.CharField(max_length=255, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_to_domain",
                        to="mail_servers.session",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mail_servers.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=255, null=True)),
                ("port", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_to_proxy",
                        to="mail_servers.session",
                    ),
                ),
            ],
            options={
                "db_table": "proxy",
                "indexes": [
                    models.Index(
                        fields=["session", "ip"], name="proxy_session_60f2ed_idx"
                    ),
                    models.Index(fields=["status"], name="proxy_status_cf85bb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=255, null=True)),
                ("last", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=150, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_to_base",
                        to="mail_servers.session",
                    ),
                ),
            ],
            options={
                "db_table": "bases",
                "indexes": [
                    models.Index(
                        fields=["session", "email"], name="bases_session_212a23_idx"
                    ),
                    models.Index(fields=["status"], name="bases_status_c41e09_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settings_type", models.CharField(max_length=255)),
                ("data", models.IntegerField(null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_to_setting",
                        to="mail_servers.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "settings_type")},
            },
        ),
    ]
