# Generated by Django 5.0.6 on 2024-07-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_blacklistedaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_one_time_jwt_created",
            field=models.BooleanField(default=False, verbose_name="One-time JWT created"),
        ),
    ]
