# Generated by Django 5.0.6 on 2024-07-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_one_time_jwt_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("-id",),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
