# Generated by Django 5.0.6 on 2024-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_max_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
