# Generated by Django 5.0.6 on 2024-07-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usertariff"),
        ("users", "0005_user_jwt_max_out"),
    ]

    operations = []
