# Generated by Django 5.0.6 on 2024-07-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_0003_usertariff_0005_user_jwt_max_out"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertariff",
            options={
                "verbose_name": "User`s tariff",
                "verbose_name_plural": "User`s tariffs",
            },
        ),
    ]
