# flake8: noqa
# Generated by Django 5.0.6 on 2024-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("stuff", "STUFF"),
                    ("admin", "ADMIN"),
                    ("user", "USER"),
                    ("owner_company", "OWNER_COMPANY"),
                ],
                default="user",
            ),
        ),
    ]
