version: "3.9"

x-backend-environment: &backend-environment
  DJANGO_SETTINGS_MODULE: settings.settings.prod
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0

x-backend-base: &backend-base
  build:
    context: .
    dockerfile: ./Dockerfile
  volumes:
    - ./src:/mmb/src
   #  - ./:/mmb
    - ./logs:/mmb/logs/
    - ./scripts:/mmb/scripts/
    - ./src/static:/mmb/src/static/
    - ./src/media:/mmb/src/media/

x-backend: &backend
  image: app:django
  <<: *backend-base
  environment:
    <<: *backend-environment

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mega_mailer
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=mega_mailer
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    ports:
      - "8001:8001"
    networks:
      - default

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mega_mailer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:alpine
    container_name: mm_redis
    ports:
      - 6380:6379

  # Django WSGI App
  wsgi-server:
    <<: *backend
    ports:
      - 8000:8000
    links:
      - redis
    container_name: mm_wsgi
    environment:
      - RUN_IN_DOCKER=True
      - SQL_HOST=db
      - SQL_PORT=5432
    command: >
     sh -c "./scripts/wait-for-it.sh db:5432 -- sh ./scripts/entrypoint-wsgi-web.sh"

  # Celery
  celery-worker-beat:
    restart: always
    <<: *backend
    command: >
      sh -c "./scripts/wait-for-it.sh db:5432 -- sh ./scripts/entrypoint-worker.sh"
    volumes:
      - .:/mmb
    container_name: mm_celery
    environment:
      - SQL_HOST=db
      - SQL_PORT=5432
      - DJANGO_SETTINGS_MODULE=settings.settings.prod
    links:
      - redis
    depends_on:
      - redis
      - wsgi-server

  # Flower
  flower:
    <<: *backend
    command: >
      sh -c "./scripts/wait-for-it.sh db:5432 -- sh ./scripts/entrypoint-flower.sh"
    volumes:
      - .:/mmb
    ports:
      - 5555:5555
    links:
      - redis
      - celery-worker-beat
    container_name: mm_flower
    depends_on:
      - wsgi-server
      - redis
      - celery-worker-beat

networks:
  default:
    name: mega_mailer_network
    driver: bridge

volumes:
  db_data:
