version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./static:/mm-back/static
      - .:/mm-back
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "8000:8000"
    command: ./scripts/start_django.sh
    networks:
      - mega_mailer_network

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - mega_mailer_network

  redis:
    image: redis:7.2
    container_name: mm_redis
    ports:
      - "6379:6379"
    restart: always
    command: >
      --requirepass ${REDIS_PASS}
    networks:
      - mega_mailer_network

  # Django WSGI App
  asgi-server:
    image: mm-back-app:latest
    container_name: mm_asgi
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/mm-back
    depends_on:
      - db
      - redis
    command: ./scripts/start_dj_sockets.sh
    networks:
      - mega_mailer_network


  # Flower
  flower:
    image: mm-back-app:latest
    command: ["sh", "./scripts/entrypoint-flower.sh"]
    volumes:
      - .:/mmb
    ports:
      - "5555:5555"
    container_name: mm_flower
    restart: always
    depends_on:
      - app
      - redis
    networks:
      - mega_mailer_network

networks:
  mega_mailer_network:
    external: true

volumes:
  db_data:
