services:
  mm-back-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mm-back-web
    volumes:
      - .:/mm-back
      - /home/mm-back_static:/mm-back/staticfiles
      - /home/mm-back_logs:/mm-back/logs
    depends_on:
      - db
      - redis
      - ollama
    restart: always
    ports:
      - "8000:8000"
    command: ./scripts/start_django.sh
    networks:
      - mega_mailer_network

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - mega_mailer_network

  redis:
    image: redis:latest
    container_name: mm_redis
    ports:
      - "6379:6379"
    restart: always
    command: >
      --requirepass ${REDIS_PASS}
    networks:
      - mega_mailer_network


  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts:/scripts
    networks:
      - mega_mailer_network
    entrypoint: ["/bin/sh", "-c", "./scripts/entrypoint-ollama.sh"]
    environment:
      - OLLAMA_CTX_SIZE=1024
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_QUEUE=256
      - OLLAMA_KEEP_ALIVE=10m


  # Django WSGI App
  mm_back-socket:
    image: mvp-back-mm-back-web:latest
    container_name: mm-back-socket
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/mm-back
    depends_on:
      - db
      - redis
      - ollama
    command: ./scripts/start_dj_sockets.sh
    networks:
      - mega_mailer_network

  # Flower
  flower:
    image: mvp-back-mm-back-web:latest
    command: ["sh", "./scripts/entrypoint-flower.sh"]
    volumes:
      - .:/mmb
    ports:
      - "5555:5555"
    container_name: mm_flower
    restart: always
    depends_on:
      - mm-back-web
      - redis
    networks:
      - mega_mailer_network

networks:
  mega_mailer_network:
    external: true

volumes:
  db_data:
  ollama_data:
