version: "3.9"

# Общие параметры окружения для бэкэнда
x-backend-environment: &backend-environment
  DJANGO_SETTINGS_MODULE: settings.settings.prod
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0

# Базовые параметры для бэкэнда
x-backend-base: &backend-base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/np
    - ./logs:/mm/logs/
    - ./scripts:/mm/scripts/
    - ./src/static:/mm/src/static/
    - ./src/media:/mm/src/media/

# Параметры бэкэнда
x-backend: &backend
  image: app:django
  <<: *backend-base
  environment:
    <<: *backend-environment

services:
  redis:
    image: redis:alpine
    container_name: np1_redis
    ports:
      - 6365:6349
    networks:
      - common_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: np_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    networks:
      - common_network

  wsgi-server:
    <<: *backend
    ports:
      - 8001:8000
    depends_on:
      - pgadmin
      - redis
    networks:
      - common_network
    env_file:
      - .env
    command: >
      sh -c "chmod +x ./scripts/wait-for-it.sh && ./scripts/wait-for-it.sh pgadmin:5432 -- sh ./scripts/entrypoint-wsgi-web.sh"

networks:
  common_network:
    driver: bridge
