# Generated by Django 5.0.6 on 2025-01-26 22:03

import apps.backend_mailer.fields
import apps.backend_mailer.models
import apps.backend_mailer.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_email",
                    models.CharField(
                        max_length=254,
                        validators=[
                            apps.backend_mailer.validators.validate_email_with_name
                        ],
                        verbose_name="Email From",
                    ),
                ),
                (
                    "to",
                    apps.backend_mailer.fields.CommaSeparatedEmailField(
                        blank=True, verbose_name="Email To"
                    ),
                ),
                (
                    "cc",
                    apps.backend_mailer.fields.CommaSeparatedEmailField(
                        blank=True, verbose_name="Cc"
                    ),
                ),
                (
                    "bcc",
                    apps.backend_mailer.fields.CommaSeparatedEmailField(
                        blank=True, verbose_name="Bcc"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=989, verbose_name="Subject"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "html_message",
                    models.TextField(blank=True, verbose_name="HTML Message"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "sent"),
                            (1, "failed"),
                            (2, "queued"),
                            (3, "requeued"),
                        ],
                        db_index=True,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(0, "low"), (1, "medium"), (2, "high"), (3, "now")],
                        null=True,
                        verbose_name="Priority",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="The scheduled sending time",
                        null=True,
                        verbose_name="Scheduled Time",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Email won't be sent after this timestamp",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Message-ID",
                    ),
                ),
                (
                    "number_of_retries",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "headers",
                    models.JSONField(blank=True, null=True, verbose_name="Headers"),
                ),
                (
                    "context",
                    models.JSONField(blank=True, null=True, verbose_name="Context"),
                ),
                (
                    "backend_alias",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=70,
                        verbose_name="Backend alias",
                    ),
                ),
                (
                    "backend_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Backend Config",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.backend_mailer.models.get_upload_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The original filename",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                ("mimetype", models.CharField(blank=True, default="", max_length=255)),
                (
                    "headers",
                    models.JSONField(blank=True, null=True, verbose_name="Headers"),
                ),
                (
                    "emails",
                    models.ManyToManyField(
                        related_name="attachments",
                        to="backend_mailer.email",
                        verbose_name="Emails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g: 'welcome_email'",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this template.",
                        verbose_name="Description",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[
                            apps.backend_mailer.validators.validate_template_syntax
                        ],
                        verbose_name="Subject",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        validators=[
                            apps.backend_mailer.validators.validate_template_syntax
                        ],
                        verbose_name="Content",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        blank=True,
                        validators=[
                            apps.backend_mailer.validators.validate_template_syntax
                        ],
                        verbose_name="HTML content",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Render template in alternative language",
                        max_length=12,
                        verbose_name="Language",
                    ),
                ),
                (
                    "default_template",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translated_templates",
                        to="backend_mailer.emailtemplate",
                        verbose_name="Default template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ["name"],
                "unique_together": {("name", "language", "default_template")},
            },
        ),
        migrations.AddField(
            model_name="email",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend_mailer.emailtemplate",
                verbose_name="Email template",
            ),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "sent"), (1, "failed")], verbose_name="Status"
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Exception type"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "email",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="backend_mailer.email",
                        verbose_name="Email address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
            },
        ),
    ]
