# Generated by Django 5.0.6 on 2025-01-29 12:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_mailer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailbackend",
            name="mailing_type",
        ),
        migrations.AddField(
            model_name="email",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_to_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailbackend",
            name="backend_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "django.core.mail.backends.smtp.EmailBackend"),
                    (2, "django_ses.SESBackend"),
                    (3, "django.core.mail.backends.smtp.EmailBackend"),
                    (4, "anymail.backends.amazon_ses.EmailBackend"),
                ],
                default=1,
                help_text="Backend mailing type",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="bcc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                help_text="Bcc",
                null=True,
                size=None,
                verbose_name="Bcc",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="cc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                help_text="Cc",
                null=True,
                size=None,
                verbose_name="Cc",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (4, "created"),
                    (0, "sent"),
                    (1, "failed"),
                    (2, "queued"),
                    (3, "requeued"),
                ],
                db_index=True,
                default=4,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                help_text="Email To",
                null=True,
                size=None,
                verbose_name="Email To",
            ),
        ),
    ]
