# Generated by Django 5.0.6 on 2025-01-28 22:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_mailer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="bcc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                help_text="Bcc",
                null=True,
                size=None,
                verbose_name="Bcc",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="cc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                help_text="Cc",
                null=True,
                size=None,
                verbose_name="Cc",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (4, "created"),
                    (0, "sent"),
                    (1, "failed"),
                    (2, "queued"),
                    (3, "requeued"),
                ],
                db_index=True,
                default=4,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                help_text="Email To",
                null=True,
                size=None,
                verbose_name="Email To",
            ),
        ),
    ]
