# Generated by Django 5.0.6 on 2025-02-07 10:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend_mailer",
            "0002_remove_emailbackend_mailing_type_email_author_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SentMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        help_text="Email To",
                        null=True,
                        size=None,
                        verbose_name="Email To",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (4, "created"),
                            (0, "sent"),
                            (1, "failed"),
                            (2, "queued"),
                            (3, "requeued"),
                        ],
                        db_index=True,
                        default=4,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend_mailer.email",
                    ),
                ),
            ],
            options={
                "verbose_name": "SentMessages",
                "verbose_name_plural": "SentMessages",
            },
        ),
    ]
