# Generated by Django 5.0.6 on 2025-02-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_mailer", "0004_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Promotional", "Promotional"),
                    ("Transactional", "Transactional"),
                    ("Newsletter", "Newsletter"),
                ],
                default="Promotional",
                max_length=30,
                verbose_name="Template Type",
            ),
        ),
    ]
