# Generated by Django 5.0.6 on 2025-02-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_mailer", "0005_emailtemplate_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtemplate",
            old_name="type",
            new_name="template_type",
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="template_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Draft", "Draft"),
                    ("Archived", "Archived"),
                ],
                default="Draft",
                max_length=30,
                verbose_name="Template Status",
            ),
        ),
    ]
