# Generated by Django 5.0.6 on 2024-07-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IMAPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                ("url", models.URLField()),
                ("port", models.IntegerField()),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "username",
                    models.EmailField(
                        blank=True,
                        default="default_smtp@example.com",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("email_use_tls", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "IMAPServer",
                "verbose_name_plural": "IMAPServers",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "from_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("template", models.TextField(blank=True, null=True)),
                ("message", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MessageTemplate",
                "verbose_name_plural": "MessageTemplates",
            },
        ),
        migrations.CreateModel(
            name="ProxyServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                ("url", models.URLField()),
                ("port", models.IntegerField()),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "username",
                    models.EmailField(
                        blank=True,
                        default="default_smtp@example.com",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("email_use_tls", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "IMAPServer",
                "verbose_name_plural": "IMAPServers",
            },
        ),
        migrations.CreateModel(
            name="SMTPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                ("url", models.URLField()),
                ("port", models.IntegerField()),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "username",
                    models.EmailField(
                        blank=True,
                        default="default_smtp@example.com",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("email_use_tls", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "SMTPServer",
                "verbose_name_plural": "SMTPServers",
            },
        ),
    ]
