# Generated by Django 5.0.6 on 2024-07-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_servers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IMAPServer",
        ),
        migrations.DeleteModel(
            name="ProxyServer",
        ),
        migrations.DeleteModel(
            name="SMTPServer",
        ),
    ]
