# Generated by Django 5.0.6 on 2024-07-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_servers", "0002_messagetemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imapserver",
            name="queries_per_sec",
        ),
        migrations.RemoveField(
            model_name="proxyserver",
            name="queries_per_sec",
        ),
        migrations.RemoveField(
            model_name="smtpserver",
            name="queries_per_sec",
        ),
    ]
