# Generated by Django 5.0.6 on 2024-07-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_servers", "0003_server_imapserver_proxyserver_smtpserver"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proxyserver",
            options={
                "verbose_name": "ProxyServer",
                "verbose_name_plural": "ProxyServers",
            },
        ),
    ]
