# Generated by Django 5.0.6 on 2024-07-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_servers", "0004_alter_proxyserver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imapserver",
            options={
                "verbose_name": "IMAP server",
                "verbose_name_plural": "IMAP servers",
            },
        ),
        migrations.AlterModelOptions(
            name="proxyserver",
            options={
                "verbose_name": "Proxy server",
                "verbose_name_plural": "Proxy servers",
            },
        ),
        migrations.AlterModelOptions(
            name="smtpserver",
            options={
                "verbose_name": "SMTP server",
                "verbose_name_plural": "SMTP servers",
            },
        ),
    ]
