# Generated by Django 5.0.6 on 2024-07-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mail_servers",
            "0005_alter_imapserver_options_alter_proxyserver_options_and_more",
        ),
        ("mailers", "0004_messagetemplate_alter_sentmessage_template"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MessageTemplate",
        ),
    ]
