# Generated by Django 5.0.6 on 2024-07-12 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelog", "0002_remove_changelog_data_changes_changelog_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changelog",
            options={
                "ordering": ("changed",),
                "verbose_name": "Change log",
                "verbose_name_plural": "Change logs",
            },
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="action",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="url",
        ),
        migrations.AddField(
            model_name="changelog",
            name="action_on_model",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                max_length=50,
                null=True,
                verbose_name="Action",
            ),
        ),
        migrations.AddField(
            model_name="changelog",
            name="changed",
            field=models.DateTimeField(auto_now=True, verbose_name="Date/time of change"),
        ),
        migrations.AddField(
            model_name="changelog",
            name="ipaddress",
            field=models.CharField(max_length=15, null=True, verbose_name="IP address"),
        ),
        migrations.AddField(
            model_name="changelog",
            name="model",
            field=models.CharField(max_length=255, null=True, verbose_name="Table"),
        ),
        migrations.AddField(
            model_name="changelog",
            name="record_id",
            field=models.IntegerField(null=True, verbose_name="ID of the record"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="data",
            field=models.JSONField(default=dict, verbose_name="Variable model data"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author of the change",
            ),
        ),
    ]
