# Generated by Django 5.0.6 on 2025-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "created"),
                    (1, "started"),
                    (2, "Completed"),
                    (3, "Stopped"),
                    (4, "Error"),
                    (5, "AI Mailing"),
                    (6, "Sending"),
                ],
                default=0,
                help_text="Campaign status",
            ),
        ),
    ]
