# Generated by Django 5.0.6 on 2025-02-11 22:23

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailers", "0003_alter_campaign_campaign_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="country_tag",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="message_type",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="shipping_type",
        ),
        migrations.AddField(
            model_name="campaign",
            name="campaign_tag",
            field=models.CharField(
                blank=True,
                help_text="Campaign tag",
                max_length=100,
                null=True,
                verbose_name="Campaign tag",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, help_text="Campaign country", max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="email_content",
            field=models.TextField(blank=True, help_text="Email content", null=True),
        ),
    ]
