# Generated by Django 5.0.6 on 2025-02-02 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Judge",
                "verbose_name_plural": "Judges",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                ("host", models.CharField(max_length=15)),
                ("port", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("country_code", models.CharField(blank=True, max_length=5, null=True)),
                ("anonymity", models.CharField(blank=True, max_length=15, null=True)),
                ("timeout", models.PositiveIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxy",
                "verbose_name_plural": "Proxies",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProxyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                ("timeout", models.PositiveSmallIntegerField()),
                (
                    "anonymity",
                    models.CharField(
                        choices=[
                            ("TRANSPARENT", "Transparent"),
                            ("ELITE", "Elite"),
                            ("ANONYMOUS", "Anonymous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("countries", models.ManyToManyField(to="proxies.country")),
                ("judge", models.ManyToManyField(to="proxies.judge")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
