# Generated by Django 5.0.6 on 2025-02-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proxy",
            name="country",
        ),
        migrations.AddField(
            model_name="proxy",
            name="countries",
            field=models.ManyToManyField(blank=True, null=True, to="proxies.country"),
        ),
        migrations.AlterField(
            model_name="proxyconfig",
            name="anonymity",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Transparent"), (1, "Elite"), (2, "Anonymous")]
            ),
        ),
    ]
