# Generated by Django 5.0.6 on 2025-02-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_servers", "0002_alter_server_type"),
        ("smtp_checker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smtpcheckertask",
            name="servers",
            field=models.ManyToManyField(
                related_name="check_tasks", to="mail_servers.server"
            ),
        ),
        migrations.AlterField(
            model_name="smtpcheckertaskresult",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="mail_servers.server",
            ),
        ),
    ]
