# Generated by Django 5.0.6 on 2025-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smtp_checker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("recipients_queue", models.IntegerField(default=0)),
                ("smtp_in_clipboard", models.IntegerField(default=0)),
                ("sending_per_minute", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Task Statistics",
                "verbose_name_plural": "Task Statistics",
            },
        ),
    ]
