# Generated by Django 5.0.6 on 2025-02-18 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smtp_checker", "0002_taskstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtpcheckertask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
