# Generated by Django 5.0.6 on 2025-02-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smtp_checker", "0003_smtpcheckertask_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatistics",
            name="smtp_check_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskstatistics",
            name="smtp_check_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskstatistics",
            name="total_smtp_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taskstatistics",
            name="valid_smtp_count",
            field=models.IntegerField(default=0),
        ),
    ]
