# Generated by Django 5.0.6 on 2025-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("stuff", "STUFF"),
                    ("admin", "ADMIN"),
                    ("user", "USER"),
                    ("owner_company", "OWNER_COMPANY"),
                    ("support", "SUPPORT"),
                ],
                default="user",
                max_length=255,
            ),
        ),
    ]
