# Generated by Django 5.0.6 on 2025-02-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar_user_bio_user_birth_date_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram ID"
            ),
        ),
    ]
