# Generated by Django 5.0.6 on 2025-02-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[("new", "New"), ("member", "Member"), ("sale", "Sale")],
                default="new",
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("tech", "Tech"),
                    ("staff", "Staff"),
                    ("super_staff", "Super_staff"),
                    ("admin", "ADMIN"),
                ],
                default="user",
                max_length=55,
            ),
        ),
    ]
