# Generated by Django 5.0.6 on 2025-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_position_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.AddField(
            model_name="user",
            name="mailing_experience",
            field=models.CharField(
                choices=[
                    ("no_experience", "No experience"),
                    ("one_year", "1 year"),
                    ("three_years", "3 years"),
                    ("five_years", "5+ years"),
                ],
                default="no_experience",
                max_length=55,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="working_area",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("office", "Office"),
                    ("hybrid", "Hybrid"),
                ],
                default="remote",
                max_length=55,
            ),
        ),
    ]
