# Generated by Django 5.0.6 on 2025-02-24 13:00

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_gender_user_mailing_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="mailing_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_experience", "No experience"),
                    ("one_year", "1 year"),
                    ("three_years", "3 years"),
                    ("five_years", "5+ years"),
                ],
                default="no_experience",
                max_length=55,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="working_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("remote", "Remote"),
                    ("office", "Office"),
                    ("hybrid", "Hybrid"),
                ],
                default="remote",
                max_length=55,
                null=True,
            ),
        ),
    ]
