# Generated by Django 5.0.6 on 2025-01-26 11:35

import django.db.models.deletion
import utils.model_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBackend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "mailing_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Default"),
                            (2, "SES"),
                            (3, "AnyMail 3"),
                            (4, "SMTP"),
                            (5, "G-Mail 5"),
                        ],
                        help_text="Backend mailing type",
                    ),
                ),
                (
                    "config",
                    utils.model_fields.EncryptedJSONField(
                        help_text="User config for chosen backend"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backend_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "EmailBackend",
                "verbose_name_plural": "EmailBackend",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "campaign_id",
                    models.CharField(
                        help_text="Campaign id from user", max_length=100, unique=True
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(help_text="Campaign name", max_length=100),
                ),
                (
                    "shipping_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Default"), (2, "Speed"), (3, "Extra speed")],
                        help_text="Campaign shipping type",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "New"),
                            (2, "Completed"),
                            (3, "Stopped"),
                            (4, "Error"),
                            (5, "AI mailing"),
                            (6, "Sending"),
                        ],
                        default=1,
                        help_text="Campaign shipping type",
                    ),
                ),
                (
                    "visitors",
                    models.IntegerField(default=0, help_text="Visitor clicks"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "email_backend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_to_backend",
                        to="campaign.emailbackend",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaign",
            },
        ),
    ]
