# Generated by Django 5.0.6 on 2024-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailers", "0002_sentmessage_server_alter_sentmessage_template_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentmessage",
            options={
                "verbose_name": "Sent message",
                "verbose_name_plural": "Sent messages",
            },
        ),
        migrations.AddField(
            model_name="sentmessage",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
    ]
