# Generated by Django 5.0.6 on 2024-07-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailers", "0003_alter_sentmessage_options_sentmessage_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "from_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("template", models.TextField(blank=True, null=True)),
                ("message", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MessageTemplate",
                "verbose_name_plural": "MessageTemplates",
            },
        ),
        migrations.AlterField(
            model_name="sentmessage",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mailers.messagetemplate",
            ),
        ),
    ]
