# Generated by Django 5.0.6 on 2024-07-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailers", "0004_messagetemplate_alter_sentmessage_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagetemplate",
            options={
                "verbose_name": "Message template",
                "verbose_name_plural": "Message templates",
            },
        ),
    ]
