# Generated by Django 5.0.6 on 2024-07-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_created_at_product_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
