# Generated by Django 5.0.6 on 2025-02-08 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="imap_port",
            field=models.IntegerField(
                default=993,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="imap_server",
            field=models.CharField(default="imap.gmail.com", max_length=255),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
