# Generated by Django 5.0.6 on 2025-02-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(default="", max_length=500)),
                (
                    "notify_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Order"),
                            (1, "Payment"),
                            (2, "Item"),
                            (3, "General"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("data", models.JSONField(default=dict, help_text="Any useful data.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
